#ifndef OPTIONS_H
#define OPTIONS_H

#include <string>

// DB open options
class Options {
public:
    Options();

    // If true, the database will be created if it is missing.
    bool create_if_missing;

    // If true, an error is raised if the database already exists.
    bool error_if_exists;

    // If true, the implementation will do aggressive checking of the
    // data it is processing and will stop early if it detects any
    // errors.  This may have unforeseen ramifications: for example, a
    // corruption of one DB entry may cause a large number of entries to
    // become unreadable or for the entire DB to become unopenable.
    bool paranoid_checks;

    // Any internal progress/error information generated by the db will
    // be written to info_log if it is non-null, or to a file stored
    // in the same directory as the DB contents if info_log is null.
    // Default: nullptr
    std::string* info_log;

    // Amount of data to build up in memory before converting to a sorted
    // on-disk file.  Larger values increase performance, especially during
    // bulk loads.  Up to two write buffers may be held in memory at the
    // same time, so you may wish to adjust this parameter to control
    // memory usage.  Also, a larger write buffer will result in a longer
    // recovery time the next time the database is opened.
    // Default: 4MB
    size_t write_buffer_size;
};

// Options that control read operations
class ReadOptions {
public:
    ReadOptions();

    // If true, all data read from underlying storage will be
    // verified against corresponding checksums.
    bool verify_checksums;

    // Should the data read for this iteration be cached in memory?
    // Callers may wish to set this field to false for bulk scans.
    bool fill_cache;

    // If "snapshot" is non-null, read as of the supplied snapshot
    // (which must belong to the DB that is being read and which must
    // not have been released).  If "snapshot" is null, use an implicit
    // snapshot of the state at the beginning of this read operation.
    // Default: nullptr
    const void* snapshot;
};

// Options that control write operations
class WriteOptions {
public:
    WriteOptions();

    // If true, the write will be flushed from the operating system
    // buffer cache (by calling WritableFile::Sync()) before the write
    // is considered complete.  If this flag is true, writes will be
    // slower.
    //
    // If this flag is false, and the machine crashes, some recent
    // writes may be lost.  Note that if it is just the process that
    // crashes (i.e., the machine does not reboot), no writes will be
    // lost even if sync==false.
    //
    // In other words, a DB write with sync==false has similar
    // crash semantics as the "write()" system call.  A DB write
    // with sync==true has similar crash semantics to a "write()"
    // system call followed by "fsync()".
    bool sync;
};

#endif // OPTIONS_H